name: Test AI Agent (Genesis)

on:
  workflow_dispatch:
  push:
    branches:
      - genesis-self-evolving-ai  # Runs only on this branch

jobs:
  test-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Test Script (OpenRouter API)
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: |
        python agents/paper_reader_agent.py
