name: Run OpenRouter AI Agent

on:
  workflow_dispatch:  # Allows manual run from GitHub UI
  push:
    branches:
      - openrouter-ai-agent  # Automatically triggers on push to this branch

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run OpenRouter Agent Script
      env:
        API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        PROMPT: "What is the meaning of life?"
      run: |
        python agent.py
